#pragma once
#include <stdbool.h>

#define NBLOCK 5
#define SQ_POWER 256
#define DOMAIN_SEP "ORISIGN"
#define HASHES_BYTES 32
#define SALT_LEN 16

#define FP_BYTES ((NBLOCK-1) * 8)
#define FP2_BYTES (2 * FP_BYTES)
#define FP2_SIGNC 3
#define COMPRESSED_SIG_SIZE (HASHES_BYTES + SALT_LEN + (FP2_SIGNC * FP2_BYTES))

#define KAT_SEED_SIZE 64
#define KAT_LABEL "BBBBBBBBBBBBBLINDDDDDDDDDDDD"
#define KAT_MAX_COUNTER 0xFFFFFFFFFFFFFFFFULL

