#pragma once
#include <stdbool.h>

#define NBLOCK 1
#define SQ_POWER 8
#define ORISIGN_DOMAIN_SEP "ORISIGN-V9.7-NIST-PQC-2026"

#define FP_BYTES (NBLOCK * 8)
#define FP2_BYTES (2 * FP_BYTES)
#define COMPRESSED_SIG_SIZE (FP_BYTES + (6 * FP2_BYTES))

#define NORM_TOLERANCE_UPPER 1.15
#define NORM_TOLERANCE_LOWER 0.85
#define NORM_TOLERANCE_LIMIT 0.80

#define MAX_SIGN_ATTEMPTS 1000
#define MAX_SIGN_RESETS 50

#define KAT_SEED_SIZE 64
#define KAT_LABEL "BBBBBBBBBBBBBLINDDDDDDDDDDDD"
#define KAT_MAX_COUNTER 0xFFFFFFFFFFFFFFFFULL

